// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'core/services/local_database/attendance/attendance_entity.dart';
import 'core/services/local_database/outstanding_task/outstanding_task_entity.dart';
import 'core/services/local_database/site_condition/site_condition_entity.dart';
import 'core/services/local_database/tire_inspect_picture/tire_inspect_picture_entity.dart';
import 'core/services/local_database/tire_inspection_draft/tire_inspection_draft_entity.dart';
import 'core/services/local_database/tire_inspection_offline_edit/tire_inspection_offline_edit_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 1247165417930296300),
      name: 'OutstandingTaskEntity',
      lastPropertyId: const IdUid(15, 553556009570233128),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 1327459534982566706),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 4261125030613470334),
            name: 'unit',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 6857417009274331136),
            name: 'serialNumber',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 8767027067182524262),
            name: 'tireSize',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 5175264704332265189),
            name: 'position',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 3843587922974642998),
            name: 'tireDamage',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 4300580738487652109),
            name: 'remarks',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 1216653518039429250),
            name: 'condition',
            type: 30,
            flags: 0),
        ModelProperty(
            id: const IdUid(9, 7560146528010113624),
            name: 'pressure',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(10, 5013486904149079187),
            name: 'idSite',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(11, 2753554739486871542),
            name: 'user',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(12, 188914959695792532),
            name: 'lastUpdate',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(13, 6302964802626941762),
            name: 'isDone',
            type: 1,
            flags: 0),
        ModelProperty(
            id: const IdUid(14, 6506732159611965303),
            name: 'idTask',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(15, 553556009570233128),
            name: 'brand',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(2, 4847767954173900942),
      name: 'AttendanceEntity',
      lastPropertyId: const IdUid(13, 7744846828465339842),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 272198496252705597),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(6, 665925264274010934),
            name: 'date',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 1484614968790516581),
            name: 'masuk',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 1924472974290556446),
            name: 'keluar',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(10, 7954331026111298020),
            name: 'masukImage',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(11, 1304923070146106978),
            name: 'keluarImage',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(12, 1190013883963276794),
            name: 'keteranganMasuk',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(13, 7744846828465339842),
            name: 'keteranganKeluar',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(3, 2481607064593893714),
      name: 'TireInspectPictureEntity',
      lastPropertyId: const IdUid(3, 3754108111333411994),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 559766504538233270),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 4804705467211053688),
            name: 'idImage',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 3754108111333411994),
            name: 'image',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(4, 1532226628722020044),
      name: 'SiteConditionEntity',
      lastPropertyId: const IdUid(9, 8608723263995913600),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 483597318480856548),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 8315105565570580933),
            name: 'name',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 5592767056786396245),
            name: 'latitude',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 7157923189098878148),
            name: 'longitude',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 5506902624774073560),
            name: 'remarks',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 2241240998231815699),
            name: 'date',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 636548642260981471),
            name: 'image',
            type: 30,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 6097711016615018336),
            name: 'siteConditionId',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(6, 3707612730663693188),
      name: 'TireInspectionDraftEntity',
      lastPropertyId: const IdUid(17, 1044897928696218749),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 3921162149749741710),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 829980885628662138),
            name: 'storageToken',
            type: 9,
            flags: 2080,
            indexId: const IdUid(2, 3257553517996472036)),
        ModelProperty(
            id: const IdUid(3, 7106272875332196455),
            name: 'userId',
            type: 9,
            flags: 2048,
            indexId: const IdUid(3, 571721907201197778)),
        ModelProperty(
            id: const IdUid(4, 6652552876791487738),
            name: 'siteId',
            type: 9,
            flags: 2048,
            indexId: const IdUid(4, 1870706964490806350)),
        ModelProperty(
            id: const IdUid(5, 779729549122456904),
            name: 'unitNumber',
            type: 9,
            flags: 2048,
            indexId: const IdUid(5, 8665176081532320594)),
        ModelProperty(
            id: const IdUid(6, 4743953306098693851),
            name: 'inspectionDate',
            type: 9,
            flags: 2048,
            indexId: const IdUid(6, 3038259512425712531)),
        ModelProperty(
            id: const IdUid(7, 2657424782010689786),
            name: 'createdAtMillis',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 6655326173759908983),
            name: 'updatedAtMillis',
            type: 6,
            flags: 8,
            indexId: const IdUid(7, 8791780560457950025)),
        ModelProperty(
            id: const IdUid(9, 5877052912631046418),
            name: 'periodType',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(10, 6765686734048243021),
            name: 'location',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(11, 138760243502877056),
            name: 'hm',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(12, 7358520491326401089),
            name: 'unitModel',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(13, 6838175691880269835),
            name: 'siteName',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(14, 7504222624366807196),
            name: 'userDisplayName',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(15, 8043701271188989020),
            name: 'positionCount',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(16, 96096236899331635),
            name: 'imageCount',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(17, 1044897928696218749),
            name: 'payloadJson',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(7, 337180601686900237),
      name: 'TireInspectionOfflineEditEntity',
      lastPropertyId: const IdUid(11, 3983164961122509684),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 6005862507352071936),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 1793035355903747144),
            name: 'inspectionDocumentId',
            type: 9,
            flags: 2080,
            indexId: const IdUid(8, 7459522532285237176)),
        ModelProperty(
            id: const IdUid(3, 8891260531602556845),
            name: 'siteId',
            type: 9,
            flags: 2048,
            indexId: const IdUid(9, 9146718258176853893)),
        ModelProperty(
            id: const IdUid(4, 8212804424367248590),
            name: 'unitNumber',
            type: 9,
            flags: 2048,
            indexId: const IdUid(10, 8887781759751462120)),
        ModelProperty(
            id: const IdUid(5, 7415715201803282),
            name: 'inspectionDate',
            type: 9,
            flags: 2048,
            indexId: const IdUid(11, 4525891365673924882)),
        ModelProperty(
            id: const IdUid(6, 6399292144999723831),
            name: 'originalHari',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 2246142409640211563),
            name: 'cachedInspectionJson',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 305421651954315454),
            name: 'pendingInspectionJson',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(9, 4250010527208265906),
            name: 'pendingDailyPressureJson',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(10, 1402532595169219269),
            name: 'updatedAtMillis',
            type: 6,
            flags: 8,
            indexId: const IdUid(12, 2097185445966602181)),
        ModelProperty(
            id: const IdUid(11, 3983164961122509684),
            name: 'pendingSync',
            type: 1,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(7, 337180601686900237),
      lastIndexId: const IdUid(12, 2097185445966602181),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [3938695816533245477],
      retiredIndexUids: const [3050109029188817089],
      retiredPropertyUids: const [
        474179681657960148,
        8790142092273941776,
        270516801495845819,
        8496804746463566091,
        3932261417753447039,
        8608723263995913600,
        9079409243840037885,
        479354870416861301
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    OutstandingTaskEntity: EntityDefinition<OutstandingTaskEntity>(
        model: _entities[0],
        toOneRelations: (OutstandingTaskEntity object) => [],
        toManyRelations: (OutstandingTaskEntity object) => {},
        getId: (OutstandingTaskEntity object) => object.id,
        setId: (OutstandingTaskEntity object, int id) {
          object.id = id;
        },
        objectToFB: (OutstandingTaskEntity object, fb.Builder fbb) {
          final unitOffset = fbb.writeString(object.unit);
          final serialNumberOffset = fbb.writeString(object.serialNumber);
          final tireSizeOffset = fbb.writeString(object.tireSize);
          final tireDamageOffset = fbb.writeString(object.tireDamage);
          final remarksOffset = fbb.writeString(object.remarks);
          final conditionOffset = fbb.writeList(
              object.condition.map(fbb.writeString).toList(growable: false));
          final pressureOffset = fbb.writeString(object.pressure);
          final idSiteOffset = fbb.writeString(object.idSite);
          final userOffset = fbb.writeString(object.user);
          final lastUpdateOffset = fbb.writeString(object.lastUpdate);
          final idTaskOffset = fbb.writeString(object.idTask);
          final brandOffset = fbb.writeString(object.brand);
          fbb.startTable(16);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, unitOffset);
          fbb.addOffset(2, serialNumberOffset);
          fbb.addOffset(3, tireSizeOffset);
          fbb.addInt64(4, object.position);
          fbb.addOffset(5, tireDamageOffset);
          fbb.addOffset(6, remarksOffset);
          fbb.addOffset(7, conditionOffset);
          fbb.addOffset(8, pressureOffset);
          fbb.addOffset(9, idSiteOffset);
          fbb.addOffset(10, userOffset);
          fbb.addOffset(11, lastUpdateOffset);
          fbb.addBool(12, object.isDone);
          fbb.addOffset(13, idTaskOffset);
          fbb.addOffset(14, brandOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = OutstandingTaskEntity(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              idTask: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 30, ''),
              idSite: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 22, ''),
              user: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 24, ''),
              unit: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              serialNumber: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              tireSize: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, ''),
              condition: const fb.ListReader<String>(fb.StringReader(asciiOptimization: true),
                      lazy: false)
                  .vTableGet(buffer, rootOffset, 18, []),
              position: const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
              brand: const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 32, ''),
              tireDamage: const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 14, ''),
              remarks: const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 16, ''),
              pressure: const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 20, ''),
              lastUpdate: const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 26, ''),
              isDone: const fb.BoolReader().vTableGet(buffer, rootOffset, 28, false));

          return object;
        }),
    AttendanceEntity: EntityDefinition<AttendanceEntity>(
        model: _entities[1],
        toOneRelations: (AttendanceEntity object) => [],
        toManyRelations: (AttendanceEntity object) => {},
        getId: (AttendanceEntity object) => object.id,
        setId: (AttendanceEntity object, int id) {
          object.id = id;
        },
        objectToFB: (AttendanceEntity object, fb.Builder fbb) {
          final dateOffset = fbb.writeString(object.date);
          final masukOffset = fbb.writeString(object.masuk);
          final keluarOffset = fbb.writeString(object.keluar);
          final masukImageOffset = fbb.writeString(object.masukImage);
          final keluarImageOffset = fbb.writeString(object.keluarImage);
          final keteranganMasukOffset = fbb.writeString(object.keteranganMasuk);
          final keteranganKeluarOffset =
              fbb.writeString(object.keteranganKeluar);
          fbb.startTable(14);
          fbb.addInt64(0, object.id);
          fbb.addOffset(5, dateOffset);
          fbb.addOffset(6, masukOffset);
          fbb.addOffset(7, keluarOffset);
          fbb.addOffset(9, masukImageOffset);
          fbb.addOffset(10, keluarImageOffset);
          fbb.addOffset(11, keteranganMasukOffset);
          fbb.addOffset(12, keteranganKeluarOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = AttendanceEntity(
              date: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 14, ''),
              masuk: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 16, ''),
              masukImage: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 22, ''),
              keluar: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 18, ''),
              keluarImage: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 24, ''),
              keteranganMasuk: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 26, ''),
              keteranganKeluar: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 28, ''))
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    TireInspectPictureEntity: EntityDefinition<TireInspectPictureEntity>(
        model: _entities[2],
        toOneRelations: (TireInspectPictureEntity object) => [],
        toManyRelations: (TireInspectPictureEntity object) => {},
        getId: (TireInspectPictureEntity object) => object.id,
        setId: (TireInspectPictureEntity object, int id) {
          object.id = id;
        },
        objectToFB: (TireInspectPictureEntity object, fb.Builder fbb) {
          final idImageOffset = fbb.writeString(object.idImage);
          final imageOffset = fbb.writeString(object.image);
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, idImageOffset);
          fbb.addOffset(2, imageOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = TireInspectPictureEntity(
              idImage: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              image: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''))
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    SiteConditionEntity: EntityDefinition<SiteConditionEntity>(
        model: _entities[3],
        toOneRelations: (SiteConditionEntity object) => [],
        toManyRelations: (SiteConditionEntity object) => {},
        getId: (SiteConditionEntity object) => object.id,
        setId: (SiteConditionEntity object, int id) {
          object.id = id;
        },
        objectToFB: (SiteConditionEntity object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final remarksOffset = fbb.writeString(object.remarks);
          final dateOffset = fbb.writeString(object.date);
          final imageOffset = fbb.writeList(
              object.image.map(fbb.writeString).toList(growable: false));
          final siteConditionIdOffset = fbb.writeString(object.siteConditionId);
          fbb.startTable(10);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addFloat64(2, object.latitude);
          fbb.addFloat64(3, object.longitude);
          fbb.addOffset(4, remarksOffset);
          fbb.addOffset(5, dateOffset);
          fbb.addOffset(6, imageOffset);
          fbb.addOffset(7, siteConditionIdOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = SiteConditionEntity(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              name: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              siteConditionId: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 18, ''),
              latitude:
                  const fb.Float64Reader().vTableGet(buffer, rootOffset, 8, 0),
              longitude:
                  const fb.Float64Reader().vTableGet(buffer, rootOffset, 10, 0),
              remarks: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 12, ''),
              date: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 14, ''),
              image: const fb.ListReader<String>(
                      fb.StringReader(asciiOptimization: true),
                      lazy: false)
                  .vTableGet(buffer, rootOffset, 16, []));

          return object;
        }),
    TireInspectionDraftEntity: EntityDefinition<TireInspectionDraftEntity>(
        model: _entities[4],
        toOneRelations: (TireInspectionDraftEntity object) => [],
        toManyRelations: (TireInspectionDraftEntity object) => {},
        getId: (TireInspectionDraftEntity object) => object.id,
        setId: (TireInspectionDraftEntity object, int id) {
          object.id = id;
        },
        objectToFB: (TireInspectionDraftEntity object, fb.Builder fbb) {
          final storageTokenOffset = fbb.writeString(object.storageToken);
          final userIdOffset = fbb.writeString(object.userId);
          final siteIdOffset = fbb.writeString(object.siteId);
          final unitNumberOffset = fbb.writeString(object.unitNumber);
          final inspectionDateOffset = fbb.writeString(object.inspectionDate);
          final periodTypeOffset = fbb.writeString(object.periodType);
          final locationOffset = fbb.writeString(object.location);
          final hmOffset = fbb.writeString(object.hm);
          final unitModelOffset = fbb.writeString(object.unitModel);
          final siteNameOffset = fbb.writeString(object.siteName);
          final userDisplayNameOffset = fbb.writeString(object.userDisplayName);
          final payloadJsonOffset = fbb.writeString(object.payloadJson);
          fbb.startTable(18);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, storageTokenOffset);
          fbb.addOffset(2, userIdOffset);
          fbb.addOffset(3, siteIdOffset);
          fbb.addOffset(4, unitNumberOffset);
          fbb.addOffset(5, inspectionDateOffset);
          fbb.addInt64(6, object.createdAtMillis);
          fbb.addInt64(7, object.updatedAtMillis);
          fbb.addOffset(8, periodTypeOffset);
          fbb.addOffset(9, locationOffset);
          fbb.addOffset(10, hmOffset);
          fbb.addOffset(11, unitModelOffset);
          fbb.addOffset(12, siteNameOffset);
          fbb.addOffset(13, userDisplayNameOffset);
          fbb.addInt64(14, object.positionCount);
          fbb.addInt64(15, object.imageCount);
          fbb.addOffset(16, payloadJsonOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = TireInspectionDraftEntity(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              storageToken: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              userId: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              siteId: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, ''),
              unitNumber: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 12, ''),
              inspectionDate: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 14, ''),
              createdAtMillis:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
              updatedAtMillis:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0),
              periodType: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 20, ''),
              location: const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 22, ''),
              hm: const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 24, ''),
              unitModel: const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 26, ''),
              siteName: const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 28, ''),
              userDisplayName: const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 30, ''),
              positionCount: const fb.Int64Reader().vTableGet(buffer, rootOffset, 32, 0),
              imageCount: const fb.Int64Reader().vTableGet(buffer, rootOffset, 34, 0),
              payloadJson: const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 36, ''));

          return object;
        }),
    TireInspectionOfflineEditEntity: EntityDefinition<
            TireInspectionOfflineEditEntity>(
        model: _entities[5],
        toOneRelations: (TireInspectionOfflineEditEntity object) => [],
        toManyRelations: (TireInspectionOfflineEditEntity object) => {},
        getId: (TireInspectionOfflineEditEntity object) => object.id,
        setId: (TireInspectionOfflineEditEntity object, int id) {
          object.id = id;
        },
        objectToFB: (TireInspectionOfflineEditEntity object, fb.Builder fbb) {
          final inspectionDocumentIdOffset =
              fbb.writeString(object.inspectionDocumentId);
          final siteIdOffset = fbb.writeString(object.siteId);
          final unitNumberOffset = fbb.writeString(object.unitNumber);
          final inspectionDateOffset = fbb.writeString(object.inspectionDate);
          final originalHariOffset = fbb.writeString(object.originalHari);
          final cachedInspectionJsonOffset =
              fbb.writeString(object.cachedInspectionJson);
          final pendingInspectionJsonOffset =
              fbb.writeString(object.pendingInspectionJson);
          final pendingDailyPressureJsonOffset =
              fbb.writeString(object.pendingDailyPressureJson);
          fbb.startTable(12);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, inspectionDocumentIdOffset);
          fbb.addOffset(2, siteIdOffset);
          fbb.addOffset(3, unitNumberOffset);
          fbb.addOffset(4, inspectionDateOffset);
          fbb.addOffset(5, originalHariOffset);
          fbb.addOffset(6, cachedInspectionJsonOffset);
          fbb.addOffset(7, pendingInspectionJsonOffset);
          fbb.addOffset(8, pendingDailyPressureJsonOffset);
          fbb.addInt64(9, object.updatedAtMillis);
          fbb.addBool(10, object.pendingSync);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = TireInspectionOfflineEditEntity(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              inspectionDocumentId: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              siteId: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              unitNumber: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, ''),
              inspectionDate: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 12, ''),
              originalHari: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 14, ''),
              cachedInspectionJson: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 16, ''),
              pendingInspectionJson:
                  const fb.StringReader(asciiOptimization: true)
                      .vTableGet(buffer, rootOffset, 18, ''),
              pendingDailyPressureJson: const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 20, ''),
              updatedAtMillis: const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0),
              pendingSync: const fb.BoolReader().vTableGet(buffer, rootOffset, 24, false));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [OutstandingTaskEntity] entity fields to define ObjectBox queries.
class OutstandingTaskEntity_ {
  /// see [OutstandingTaskEntity.id]
  static final id =
      QueryIntegerProperty<OutstandingTaskEntity>(_entities[0].properties[0]);

  /// see [OutstandingTaskEntity.unit]
  static final unit =
      QueryStringProperty<OutstandingTaskEntity>(_entities[0].properties[1]);

  /// see [OutstandingTaskEntity.serialNumber]
  static final serialNumber =
      QueryStringProperty<OutstandingTaskEntity>(_entities[0].properties[2]);

  /// see [OutstandingTaskEntity.tireSize]
  static final tireSize =
      QueryStringProperty<OutstandingTaskEntity>(_entities[0].properties[3]);

  /// see [OutstandingTaskEntity.position]
  static final position =
      QueryIntegerProperty<OutstandingTaskEntity>(_entities[0].properties[4]);

  /// see [OutstandingTaskEntity.tireDamage]
  static final tireDamage =
      QueryStringProperty<OutstandingTaskEntity>(_entities[0].properties[5]);

  /// see [OutstandingTaskEntity.remarks]
  static final remarks =
      QueryStringProperty<OutstandingTaskEntity>(_entities[0].properties[6]);

  /// see [OutstandingTaskEntity.condition]
  static final condition = QueryStringVectorProperty<OutstandingTaskEntity>(
      _entities[0].properties[7]);

  /// see [OutstandingTaskEntity.pressure]
  static final pressure =
      QueryStringProperty<OutstandingTaskEntity>(_entities[0].properties[8]);

  /// see [OutstandingTaskEntity.idSite]
  static final idSite =
      QueryStringProperty<OutstandingTaskEntity>(_entities[0].properties[9]);

  /// see [OutstandingTaskEntity.user]
  static final user =
      QueryStringProperty<OutstandingTaskEntity>(_entities[0].properties[10]);

  /// see [OutstandingTaskEntity.lastUpdate]
  static final lastUpdate =
      QueryStringProperty<OutstandingTaskEntity>(_entities[0].properties[11]);

  /// see [OutstandingTaskEntity.isDone]
  static final isDone =
      QueryBooleanProperty<OutstandingTaskEntity>(_entities[0].properties[12]);

  /// see [OutstandingTaskEntity.idTask]
  static final idTask =
      QueryStringProperty<OutstandingTaskEntity>(_entities[0].properties[13]);

  /// see [OutstandingTaskEntity.brand]
  static final brand =
      QueryStringProperty<OutstandingTaskEntity>(_entities[0].properties[14]);
}

/// [AttendanceEntity] entity fields to define ObjectBox queries.
class AttendanceEntity_ {
  /// see [AttendanceEntity.id]
  static final id =
      QueryIntegerProperty<AttendanceEntity>(_entities[1].properties[0]);

  /// see [AttendanceEntity.date]
  static final date =
      QueryStringProperty<AttendanceEntity>(_entities[1].properties[1]);

  /// see [AttendanceEntity.masuk]
  static final masuk =
      QueryStringProperty<AttendanceEntity>(_entities[1].properties[2]);

  /// see [AttendanceEntity.keluar]
  static final keluar =
      QueryStringProperty<AttendanceEntity>(_entities[1].properties[3]);

  /// see [AttendanceEntity.masukImage]
  static final masukImage =
      QueryStringProperty<AttendanceEntity>(_entities[1].properties[4]);

  /// see [AttendanceEntity.keluarImage]
  static final keluarImage =
      QueryStringProperty<AttendanceEntity>(_entities[1].properties[5]);

  /// see [AttendanceEntity.keteranganMasuk]
  static final keteranganMasuk =
      QueryStringProperty<AttendanceEntity>(_entities[1].properties[6]);

  /// see [AttendanceEntity.keteranganKeluar]
  static final keteranganKeluar =
      QueryStringProperty<AttendanceEntity>(_entities[1].properties[7]);
}

/// [TireInspectPictureEntity] entity fields to define ObjectBox queries.
class TireInspectPictureEntity_ {
  /// see [TireInspectPictureEntity.id]
  static final id = QueryIntegerProperty<TireInspectPictureEntity>(
      _entities[2].properties[0]);

  /// see [TireInspectPictureEntity.idImage]
  static final idImage =
      QueryStringProperty<TireInspectPictureEntity>(_entities[2].properties[1]);

  /// see [TireInspectPictureEntity.image]
  static final image =
      QueryStringProperty<TireInspectPictureEntity>(_entities[2].properties[2]);
}

/// [SiteConditionEntity] entity fields to define ObjectBox queries.
class SiteConditionEntity_ {
  /// see [SiteConditionEntity.id]
  static final id =
      QueryIntegerProperty<SiteConditionEntity>(_entities[3].properties[0]);

  /// see [SiteConditionEntity.name]
  static final name =
      QueryStringProperty<SiteConditionEntity>(_entities[3].properties[1]);

  /// see [SiteConditionEntity.latitude]
  static final latitude =
      QueryDoubleProperty<SiteConditionEntity>(_entities[3].properties[2]);

  /// see [SiteConditionEntity.longitude]
  static final longitude =
      QueryDoubleProperty<SiteConditionEntity>(_entities[3].properties[3]);

  /// see [SiteConditionEntity.remarks]
  static final remarks =
      QueryStringProperty<SiteConditionEntity>(_entities[3].properties[4]);

  /// see [SiteConditionEntity.date]
  static final date =
      QueryStringProperty<SiteConditionEntity>(_entities[3].properties[5]);

  /// see [SiteConditionEntity.image]
  static final image = QueryStringVectorProperty<SiteConditionEntity>(
      _entities[3].properties[6]);

  /// see [SiteConditionEntity.siteConditionId]
  static final siteConditionId =
      QueryStringProperty<SiteConditionEntity>(_entities[3].properties[7]);
}

/// [TireInspectionDraftEntity] entity fields to define ObjectBox queries.
class TireInspectionDraftEntity_ {
  /// see [TireInspectionDraftEntity.id]
  static final id = QueryIntegerProperty<TireInspectionDraftEntity>(
      _entities[4].properties[0]);

  /// see [TireInspectionDraftEntity.storageToken]
  static final storageToken = QueryStringProperty<TireInspectionDraftEntity>(
      _entities[4].properties[1]);

  /// see [TireInspectionDraftEntity.userId]
  static final userId = QueryStringProperty<TireInspectionDraftEntity>(
      _entities[4].properties[2]);

  /// see [TireInspectionDraftEntity.siteId]
  static final siteId = QueryStringProperty<TireInspectionDraftEntity>(
      _entities[4].properties[3]);

  /// see [TireInspectionDraftEntity.unitNumber]
  static final unitNumber = QueryStringProperty<TireInspectionDraftEntity>(
      _entities[4].properties[4]);

  /// see [TireInspectionDraftEntity.inspectionDate]
  static final inspectionDate = QueryStringProperty<TireInspectionDraftEntity>(
      _entities[4].properties[5]);

  /// see [TireInspectionDraftEntity.createdAtMillis]
  static final createdAtMillis =
      QueryIntegerProperty<TireInspectionDraftEntity>(
          _entities[4].properties[6]);

  /// see [TireInspectionDraftEntity.updatedAtMillis]
  static final updatedAtMillis =
      QueryIntegerProperty<TireInspectionDraftEntity>(
          _entities[4].properties[7]);

  /// see [TireInspectionDraftEntity.periodType]
  static final periodType = QueryStringProperty<TireInspectionDraftEntity>(
      _entities[4].properties[8]);

  /// see [TireInspectionDraftEntity.location]
  static final location = QueryStringProperty<TireInspectionDraftEntity>(
      _entities[4].properties[9]);

  /// see [TireInspectionDraftEntity.hm]
  static final hm = QueryStringProperty<TireInspectionDraftEntity>(
      _entities[4].properties[10]);

  /// see [TireInspectionDraftEntity.unitModel]
  static final unitModel = QueryStringProperty<TireInspectionDraftEntity>(
      _entities[4].properties[11]);

  /// see [TireInspectionDraftEntity.siteName]
  static final siteName = QueryStringProperty<TireInspectionDraftEntity>(
      _entities[4].properties[12]);

  /// see [TireInspectionDraftEntity.userDisplayName]
  static final userDisplayName = QueryStringProperty<TireInspectionDraftEntity>(
      _entities[4].properties[13]);

  /// see [TireInspectionDraftEntity.positionCount]
  static final positionCount = QueryIntegerProperty<TireInspectionDraftEntity>(
      _entities[4].properties[14]);

  /// see [TireInspectionDraftEntity.imageCount]
  static final imageCount = QueryIntegerProperty<TireInspectionDraftEntity>(
      _entities[4].properties[15]);

  /// see [TireInspectionDraftEntity.payloadJson]
  static final payloadJson = QueryStringProperty<TireInspectionDraftEntity>(
      _entities[4].properties[16]);
}

/// [TireInspectionOfflineEditEntity] entity fields to define ObjectBox queries.
class TireInspectionOfflineEditEntity_ {
  /// see [TireInspectionOfflineEditEntity.id]
  static final id = QueryIntegerProperty<TireInspectionOfflineEditEntity>(
      _entities[5].properties[0]);

  /// see [TireInspectionOfflineEditEntity.inspectionDocumentId]
  static final inspectionDocumentId =
      QueryStringProperty<TireInspectionOfflineEditEntity>(
          _entities[5].properties[1]);

  /// see [TireInspectionOfflineEditEntity.siteId]
  static final siteId = QueryStringProperty<TireInspectionOfflineEditEntity>(
      _entities[5].properties[2]);

  /// see [TireInspectionOfflineEditEntity.unitNumber]
  static final unitNumber =
      QueryStringProperty<TireInspectionOfflineEditEntity>(
          _entities[5].properties[3]);

  /// see [TireInspectionOfflineEditEntity.inspectionDate]
  static final inspectionDate =
      QueryStringProperty<TireInspectionOfflineEditEntity>(
          _entities[5].properties[4]);

  /// see [TireInspectionOfflineEditEntity.originalHari]
  static final originalHari =
      QueryStringProperty<TireInspectionOfflineEditEntity>(
          _entities[5].properties[5]);

  /// see [TireInspectionOfflineEditEntity.cachedInspectionJson]
  static final cachedInspectionJson =
      QueryStringProperty<TireInspectionOfflineEditEntity>(
          _entities[5].properties[6]);

  /// see [TireInspectionOfflineEditEntity.pendingInspectionJson]
  static final pendingInspectionJson =
      QueryStringProperty<TireInspectionOfflineEditEntity>(
          _entities[5].properties[7]);

  /// see [TireInspectionOfflineEditEntity.pendingDailyPressureJson]
  static final pendingDailyPressureJson =
      QueryStringProperty<TireInspectionOfflineEditEntity>(
          _entities[5].properties[8]);

  /// see [TireInspectionOfflineEditEntity.updatedAtMillis]
  static final updatedAtMillis =
      QueryIntegerProperty<TireInspectionOfflineEditEntity>(
          _entities[5].properties[9]);

  /// see [TireInspectionOfflineEditEntity.pendingSync]
  static final pendingSync =
      QueryBooleanProperty<TireInspectionOfflineEditEntity>(
          _entities[5].properties[10]);
}
