// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'core/services/local_database/attendance/attendance_entity.dart';
import 'core/services/local_database/outstanding_task/outstanding_task_entity.dart';
import 'core/services/local_database/tire_inspect_picture/tire_inspect_picture_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 1247165417930296300),
      name: 'OutstandingTaskEntity',
      lastPropertyId: const IdUid(15, 553556009570233128),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 1327459534982566706),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 4261125030613470334),
            name: 'unit',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 6857417009274331136),
            name: 'serialNumber',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 8767027067182524262),
            name: 'tireSize',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 5175264704332265189),
            name: 'position',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 3843587922974642998),
            name: 'tireDamage',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 4300580738487652109),
            name: 'remarks',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 1216653518039429250),
            name: 'condition',
            type: 30,
            flags: 0),
        ModelProperty(
            id: const IdUid(9, 7560146528010113624),
            name: 'pressure',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(10, 5013486904149079187),
            name: 'idSite',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(11, 2753554739486871542),
            name: 'user',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(12, 188914959695792532),
            name: 'lastUpdate',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(13, 6302964802626941762),
            name: 'isDone',
            type: 1,
            flags: 0),
        ModelProperty(
            id: const IdUid(14, 6506732159611965303),
            name: 'idTask',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(15, 553556009570233128),
            name: 'brand',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(2, 4847767954173900942),
      name: 'AttendanceEntity',
      lastPropertyId: const IdUid(13, 7744846828465339842),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 272198496252705597),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(6, 665925264274010934),
            name: 'date',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 1484614968790516581),
            name: 'masuk',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 1924472974290556446),
            name: 'keluar',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(10, 7954331026111298020),
            name: 'masukImage',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(11, 1304923070146106978),
            name: 'keluarImage',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(12, 1190013883963276794),
            name: 'keteranganMasuk',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(13, 7744846828465339842),
            name: 'keteranganKeluar',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(3, 2481607064593893714),
      name: 'TireInspectPictureEntity',
      lastPropertyId: const IdUid(3, 3754108111333411994),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 559766504538233270),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 4804705467211053688),
            name: 'idImage',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 3754108111333411994),
            name: 'image',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(3, 2481607064593893714),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [
        474179681657960148,
        8790142092273941776,
        270516801495845819,
        8496804746463566091,
        3932261417753447039
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    OutstandingTaskEntity: EntityDefinition<OutstandingTaskEntity>(
        model: _entities[0],
        toOneRelations: (OutstandingTaskEntity object) => [],
        toManyRelations: (OutstandingTaskEntity object) => {},
        getId: (OutstandingTaskEntity object) => object.id,
        setId: (OutstandingTaskEntity object, int id) {
          object.id = id;
        },
        objectToFB: (OutstandingTaskEntity object, fb.Builder fbb) {
          final unitOffset = fbb.writeString(object.unit);
          final serialNumberOffset = fbb.writeString(object.serialNumber);
          final tireSizeOffset = fbb.writeString(object.tireSize);
          final tireDamageOffset = fbb.writeString(object.tireDamage);
          final remarksOffset = fbb.writeString(object.remarks);
          final conditionOffset = fbb.writeList(
              object.condition.map(fbb.writeString).toList(growable: false));
          final pressureOffset = fbb.writeString(object.pressure);
          final idSiteOffset = fbb.writeString(object.idSite);
          final userOffset = fbb.writeString(object.user);
          final lastUpdateOffset = fbb.writeString(object.lastUpdate);
          final idTaskOffset = fbb.writeString(object.idTask);
          final brandOffset = fbb.writeString(object.brand);
          fbb.startTable(16);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, unitOffset);
          fbb.addOffset(2, serialNumberOffset);
          fbb.addOffset(3, tireSizeOffset);
          fbb.addInt64(4, object.position);
          fbb.addOffset(5, tireDamageOffset);
          fbb.addOffset(6, remarksOffset);
          fbb.addOffset(7, conditionOffset);
          fbb.addOffset(8, pressureOffset);
          fbb.addOffset(9, idSiteOffset);
          fbb.addOffset(10, userOffset);
          fbb.addOffset(11, lastUpdateOffset);
          fbb.addBool(12, object.isDone);
          fbb.addOffset(13, idTaskOffset);
          fbb.addOffset(14, brandOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = OutstandingTaskEntity(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              idTask: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 30, ''),
              idSite: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 22, ''),
              user: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 24, ''),
              unit: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              serialNumber: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              tireSize: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, ''),
              condition: const fb.ListReader<String>(fb.StringReader(asciiOptimization: true),
                      lazy: false)
                  .vTableGet(buffer, rootOffset, 18, []),
              position: const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
              brand: const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 32, ''),
              tireDamage: const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 14, ''),
              remarks: const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 16, ''),
              pressure: const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 20, ''),
              lastUpdate: const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 26, ''),
              isDone: const fb.BoolReader().vTableGet(buffer, rootOffset, 28, false));

          return object;
        }),
    AttendanceEntity: EntityDefinition<AttendanceEntity>(
        model: _entities[1],
        toOneRelations: (AttendanceEntity object) => [],
        toManyRelations: (AttendanceEntity object) => {},
        getId: (AttendanceEntity object) => object.id,
        setId: (AttendanceEntity object, int id) {
          object.id = id;
        },
        objectToFB: (AttendanceEntity object, fb.Builder fbb) {
          final dateOffset = fbb.writeString(object.date);
          final masukOffset = fbb.writeString(object.masuk);
          final keluarOffset = fbb.writeString(object.keluar);
          final masukImageOffset = fbb.writeString(object.masukImage);
          final keluarImageOffset = fbb.writeString(object.keluarImage);
          final keteranganMasukOffset = fbb.writeString(object.keteranganMasuk);
          final keteranganKeluarOffset =
              fbb.writeString(object.keteranganKeluar);
          fbb.startTable(14);
          fbb.addInt64(0, object.id);
          fbb.addOffset(5, dateOffset);
          fbb.addOffset(6, masukOffset);
          fbb.addOffset(7, keluarOffset);
          fbb.addOffset(9, masukImageOffset);
          fbb.addOffset(10, keluarImageOffset);
          fbb.addOffset(11, keteranganMasukOffset);
          fbb.addOffset(12, keteranganKeluarOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = AttendanceEntity(
              date: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 14, ''),
              masuk: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 16, ''),
              masukImage: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 22, ''),
              keluar: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 18, ''),
              keluarImage: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 24, ''),
              keteranganMasuk: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 26, ''),
              keteranganKeluar: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 28, ''))
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    TireInspectPictureEntity: EntityDefinition<TireInspectPictureEntity>(
        model: _entities[2],
        toOneRelations: (TireInspectPictureEntity object) => [],
        toManyRelations: (TireInspectPictureEntity object) => {},
        getId: (TireInspectPictureEntity object) => object.id,
        setId: (TireInspectPictureEntity object, int id) {
          object.id = id;
        },
        objectToFB: (TireInspectPictureEntity object, fb.Builder fbb) {
          final idImageOffset = fbb.writeString(object.idImage);
          final imageOffset = fbb.writeString(object.image);
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, idImageOffset);
          fbb.addOffset(2, imageOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = TireInspectPictureEntity(
              idImage: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              image: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''))
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [OutstandingTaskEntity] entity fields to define ObjectBox queries.
class OutstandingTaskEntity_ {
  /// see [OutstandingTaskEntity.id]
  static final id =
      QueryIntegerProperty<OutstandingTaskEntity>(_entities[0].properties[0]);

  /// see [OutstandingTaskEntity.unit]
  static final unit =
      QueryStringProperty<OutstandingTaskEntity>(_entities[0].properties[1]);

  /// see [OutstandingTaskEntity.serialNumber]
  static final serialNumber =
      QueryStringProperty<OutstandingTaskEntity>(_entities[0].properties[2]);

  /// see [OutstandingTaskEntity.tireSize]
  static final tireSize =
      QueryStringProperty<OutstandingTaskEntity>(_entities[0].properties[3]);

  /// see [OutstandingTaskEntity.position]
  static final position =
      QueryIntegerProperty<OutstandingTaskEntity>(_entities[0].properties[4]);

  /// see [OutstandingTaskEntity.tireDamage]
  static final tireDamage =
      QueryStringProperty<OutstandingTaskEntity>(_entities[0].properties[5]);

  /// see [OutstandingTaskEntity.remarks]
  static final remarks =
      QueryStringProperty<OutstandingTaskEntity>(_entities[0].properties[6]);

  /// see [OutstandingTaskEntity.condition]
  static final condition = QueryStringVectorProperty<OutstandingTaskEntity>(
      _entities[0].properties[7]);

  /// see [OutstandingTaskEntity.pressure]
  static final pressure =
      QueryStringProperty<OutstandingTaskEntity>(_entities[0].properties[8]);

  /// see [OutstandingTaskEntity.idSite]
  static final idSite =
      QueryStringProperty<OutstandingTaskEntity>(_entities[0].properties[9]);

  /// see [OutstandingTaskEntity.user]
  static final user =
      QueryStringProperty<OutstandingTaskEntity>(_entities[0].properties[10]);

  /// see [OutstandingTaskEntity.lastUpdate]
  static final lastUpdate =
      QueryStringProperty<OutstandingTaskEntity>(_entities[0].properties[11]);

  /// see [OutstandingTaskEntity.isDone]
  static final isDone =
      QueryBooleanProperty<OutstandingTaskEntity>(_entities[0].properties[12]);

  /// see [OutstandingTaskEntity.idTask]
  static final idTask =
      QueryStringProperty<OutstandingTaskEntity>(_entities[0].properties[13]);

  /// see [OutstandingTaskEntity.brand]
  static final brand =
      QueryStringProperty<OutstandingTaskEntity>(_entities[0].properties[14]);
}

/// [AttendanceEntity] entity fields to define ObjectBox queries.
class AttendanceEntity_ {
  /// see [AttendanceEntity.id]
  static final id =
      QueryIntegerProperty<AttendanceEntity>(_entities[1].properties[0]);

  /// see [AttendanceEntity.date]
  static final date =
      QueryStringProperty<AttendanceEntity>(_entities[1].properties[1]);

  /// see [AttendanceEntity.masuk]
  static final masuk =
      QueryStringProperty<AttendanceEntity>(_entities[1].properties[2]);

  /// see [AttendanceEntity.keluar]
  static final keluar =
      QueryStringProperty<AttendanceEntity>(_entities[1].properties[3]);

  /// see [AttendanceEntity.masukImage]
  static final masukImage =
      QueryStringProperty<AttendanceEntity>(_entities[1].properties[4]);

  /// see [AttendanceEntity.keluarImage]
  static final keluarImage =
      QueryStringProperty<AttendanceEntity>(_entities[1].properties[5]);

  /// see [AttendanceEntity.keteranganMasuk]
  static final keteranganMasuk =
      QueryStringProperty<AttendanceEntity>(_entities[1].properties[6]);

  /// see [AttendanceEntity.keteranganKeluar]
  static final keteranganKeluar =
      QueryStringProperty<AttendanceEntity>(_entities[1].properties[7]);
}

/// [TireInspectPictureEntity] entity fields to define ObjectBox queries.
class TireInspectPictureEntity_ {
  /// see [TireInspectPictureEntity.id]
  static final id = QueryIntegerProperty<TireInspectPictureEntity>(
      _entities[2].properties[0]);

  /// see [TireInspectPictureEntity.idImage]
  static final idImage =
      QueryStringProperty<TireInspectPictureEntity>(_entities[2].properties[1]);

  /// see [TireInspectPictureEntity.image]
  static final image =
      QueryStringProperty<TireInspectPictureEntity>(_entities[2].properties[2]);
}
